global using OpenTK.Graphics.OpenGL4;
global using GL = OpenTK.Graphics.OpenGL4.GL;
global using Scripts;
global using Debug = Engine.Debug;
global using Engine;
global using System;
global using System.Collections.Generic;
global using System.Xml.Serialization;
global using Vector3 = Engine.Vector3;
global using MathHelper = OpenTK.Mathematics.MathHelper;